const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

/**
 * Reusable Script: Automated Strong Hash & Secret Generator
 * 
 * Usage:
 *   node scripts/reusable/generate-secrets.js [--force] [--dry-run] [--length=32]
 * 
 * Features:
 *   - Generates cryptographically secure 256-bit / 512-bit secrets (Postgres, Redis, MinIO, JWT, Service Secret).
 *   - Automatically updates/creates root .env, .env.example, and apps/server/config/passwords.yaml.
 *   - Zero external cloud dependencies, 100% self-hosted on-premise ready.
 */

function parseArgs() {
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  const dryRun = args.includes('--dry-run');
  let length = 32;

  for (const arg of args) {
    if (arg.startsWith('--length=')) {
      const parsed = parseInt(arg.split('=')[1], 10);
      if (!isNaN(parsed) && parsed >= 16) {
        length = parsed;
      }
    }
  }

  return { force, dryRun, length };
}

function generateSecureString(bytes = 32, encoding = 'hex') {
  return crypto.randomBytes(bytes).toString(encoding);
}

function generateAlphanumericPassword(length = 32) {
  const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-';
  const randomBytes = crypto.randomBytes(length);
  let result = '';
  for (let i = 0; i < length; i++) {
    result += charset[randomBytes[i] % charset.length];
  }
  return result;
}

function generateSecrets(byteLength = 32) {
  return {
    POSTGRES_DB: 'todo_dev',
    POSTGRES_USER: 'postgres',
    POSTGRES_PASSWORD: generateAlphanumericPassword(byteLength),
    REDIS_PASSWORD: generateAlphanumericPassword(byteLength),
    MINIO_ROOT_USER: 'minioadmin',
    MINIO_ROOT_PASSWORD: generateAlphanumericPassword(byteLength),
    SERVERPOD_SERVICE_SECRET: generateSecureString(32, 'hex'),
    SERVERPOD_JWT_SECRET: generateSecureString(64, 'base64url'),
    SESSION_ENCRYPTION_KEY: generateSecureString(32, 'hex'),
    AI_API_KEY: 'self_hosted_local_key',
  };
}

function buildEnvContent(secrets) {
  return `# ==============================================================================
# nodetask Environment Variables (Self-Hosted / Zero-Cloud)
# Generated at: ${new Date().toISOString()}
# ==============================================================================

# Application Environment
NODE_ENV=development
VITE_APP_ENV=development
VITE_SERVER_URL=http://localhost:8080

# 1. PostgreSQL Database Credentials (Self-Hosted Port 5432)
POSTGRES_DB=${secrets.POSTGRES_DB}
POSTGRES_USER=${secrets.POSTGRES_USER}
POSTGRES_PASSWORD=${secrets.POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# 2. Redis Distributed Cache (Self-Hosted Port 6379)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=${secrets.REDIS_PASSWORD}

# 3. MinIO S3-Compatible Object Storage (Self-Hosted Ports 9000 & 9001)
MINIO_ROOT_USER=${secrets.MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${secrets.MINIO_ROOT_PASSWORD}
MINIO_ENDPOINT=http://localhost:9000
MINIO_CONSOLE_URL=http://localhost:9001
MINIO_DEFAULT_BUCKETS=nodetask-uploads,nodetask-attachments,nodetask-avatars,nodetask-exports

# 4. Serverpod Backend Security Secrets (512-bit / 256-bit Entropy)
SERVERPOD_SERVICE_SECRET=${secrets.SERVERPOD_SERVICE_SECRET}
SERVERPOD_JWT_SECRET=${secrets.SERVERPOD_JWT_SECRET}
SESSION_ENCRYPTION_KEY=${secrets.SESSION_ENCRYPTION_KEY}

# 5. Local AI & LLM Engine (Self-Hosted Ollama / LocalAI / Private Gateway)
AI_ENDPOINT_URL=http://localhost:11434/v1
AI_API_KEY=${secrets.AI_API_KEY}
`;
}

function buildPasswordsYamlContent(secrets) {
  return `# Serverpod Passwords and Secrets (passwords.yaml)
# Auto-generated by scripts/reusable/generate-secrets.js
# Generated at: ${new Date().toISOString()}

development:
  databasePassword: '${secrets.POSTGRES_PASSWORD}'
  redisPassword: '${secrets.REDIS_PASSWORD}'
  serviceSecret: '${secrets.SERVERPOD_SERVICE_SECRET}'
  jwtSecret: '${secrets.SERVERPOD_JWT_SECRET}'
  minioPassword: '${secrets.MINIO_ROOT_PASSWORD}'
  aiApiKey: '${secrets.AI_API_KEY}'

production:
  databasePassword: '${secrets.POSTGRES_PASSWORD}'
  redisPassword: '${secrets.REDIS_PASSWORD}'
  serviceSecret: '${secrets.SERVERPOD_SERVICE_SECRET}'
  jwtSecret: '${secrets.SERVERPOD_JWT_SECRET}'
  minioPassword: '${secrets.MINIO_ROOT_PASSWORD}'
  aiApiKey: '${secrets.AI_API_KEY}'
`;
}

function run() {
  const rootDir = process.env.NODETASK_ROOT || path.resolve(__dirname, '../../');
  const { force, dryRun, length } = parseArgs();

  console.log('================================================================');
  console.log('🔐 NODETASK STRONG SECRET & ENV GENERATOR (Zero-Cloud Mode)');
  console.log('================================================================\n');

  const secrets = generateSecrets(length);

  if (dryRun) {
    console.log('[DRY-RUN] Generated Cryptographically Secure Secrets:\n');
    console.log(JSON.stringify(secrets, null, 2));
    console.log('\n[INFO] Dry run complete. No files were written.');
    return;
  }

  const envPath = path.join(rootDir, '.env');
  const envExamplePath = path.join(rootDir, '.env.example');
  const passwordsYamlPath = path.join(rootDir, 'apps/server/config/passwords.yaml');
  const passwordsExamplePath = path.join(rootDir, 'apps/server/config/passwords.example.yaml');

  const envContent = buildEnvContent(secrets);
  const passwordsYamlContent = buildPasswordsYamlContent(secrets);

  // Write .env.example
  fs.writeFileSync(envExamplePath, envContent.replace(/^([A-Z0-9_]+)=.+$/gm, '$1=your_strong_secret_here'), 'utf8');
  console.log(`✅ [CREATED] Root template: ${path.relative(rootDir, envExamplePath)}`);

  // Write passwords.example.yaml
  fs.writeFileSync(passwordsExamplePath, passwordsYamlContent.replace(/'[^']+'/g, "'template_secret_change_me'"), 'utf8');
  console.log(`✅ [CREATED] Serverpod template: ${path.relative(rootDir, passwordsExamplePath)}`);

  // Write .env
  if (!fs.existsSync(envPath) || force) {
    fs.writeFileSync(envPath, envContent, 'utf8');
    console.log(`✅ [GENERATED] Root .env: ${path.relative(rootDir, envPath)} (256-bit strong hashes)`);
  } else {
    console.log(`ℹ️ [EXISTS] Root .env already exists. Use --force to overwrite.`);
  }

  // Write passwords.yaml
  if (!fs.existsSync(passwordsYamlPath) || force) {
    const configDir = path.dirname(passwordsYamlPath);
    if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(passwordsYamlPath, passwordsYamlContent, 'utf8');
    console.log(`✅ [GENERATED] Serverpod secrets: ${path.relative(rootDir, passwordsYamlPath)} (512-bit keys)`);
  } else {
    console.log(`ℹ️ [EXISTS] Serverpod passwords.yaml already exists. Use --force to overwrite.`);
  }

  console.log('\n================================================================');
  console.log('🎉 TOÀN BỘ SECRETS ĐÃ ĐƯỢC SINH TỰ ĐỘNG THÀNH CÔNG (0 CLOUD LOCK-IN)!');
  console.log('================================================================');
}

run();
